//* This file is part of the MOOSE framework
//* https://www.mooseframework.org
//*
//* All rights reserved, see COPYRIGHT for full restrictions
//* https://github.com/idaholab/moose/blob/master/COPYRIGHT
//*
//* Licensed under LGPL 2.1, please see LICENSE for details
//* https://www.gnu.org/licenses/lgpl-2.1.html
#include "ApertureVariationTestApp.h"
#include "ApertureVariationApp.h"
#include "Moose.h"
#include "AppFactory.h"
#include "MooseSyntax.h"

template <>
InputParameters
validParams<ApertureVariationTestApp>()
{
  InputParameters params = validParams<ApertureVariationApp>();
  return params;
}

ApertureVariationTestApp::ApertureVariationTestApp(InputParameters parameters) : MooseApp(parameters)
{
  ApertureVariationTestApp::registerAll(
      _factory, _action_factory, _syntax, getParam<bool>("allow_test_objects"));
}

ApertureVariationTestApp::~ApertureVariationTestApp() {}

void
ApertureVariationTestApp::registerAll(Factory & f, ActionFactory & af, Syntax & s, bool use_test_objs)
{
  ApertureVariationApp::registerAll(f, af, s);
  if (use_test_objs)
  {
    Registry::registerObjectsTo(f, {"ApertureVariationTestApp"});
    Registry::registerActionsTo(af, {"ApertureVariationTestApp"});
  }
}

void
ApertureVariationTestApp::registerApps()
{
  registerApp(ApertureVariationApp);
  registerApp(ApertureVariationTestApp);
}

/***************************************************************************************************
 *********************** Dynamic Library Entry Points - DO NOT MODIFY ******************************
 **************************************************************************************************/
// External entry point for dynamic application loading
extern "C" void
ApertureVariationTestApp__registerAll(Factory & f, ActionFactory & af, Syntax & s)
{
  ApertureVariationTestApp::registerAll(f, af, s);
}
extern "C" void
ApertureVariationTestApp__registerApps()
{
  ApertureVariationTestApp::registerApps();
}
